"""Stable refusal codes for the Mainnet canary preparation lane.

Every refusal is machine-readable and fail-closed.  Refusal details never
contain file contents, key material, or upstream response bodies.
"""

from __future__ import annotations


class RefusalCode:
    """Frozen refusal-code namespace (string constants, never renumbered)."""

    # Release-dependency (Testnet-RC) gate
    RC_DECLARATION_ABSENT = "RC_DECLARATION_ABSENT"
    RC_DECLARATION_INVALID = "RC_DECLARATION_INVALID"
    RC_GATES_NOT_GREEN = "RC_GATES_NOT_GREEN"
    RC_COMMIT_MISMATCH = "RC_COMMIT_MISMATCH"
    RC_WASM_MISMATCH = "RC_WASM_MISMATCH"
    RC_MAINNET_WASM_UNATTESTED = "RC_MAINNET_WASM_UNATTESTED"
    SOURCE_TREE_DIRTY = "SOURCE_TREE_DIRTY"
    HISTORICAL_HASH_DRIFT = "HISTORICAL_HASH_DRIFT"
    FREEZE_MANIFEST_INVALID = "FREEZE_MANIFEST_INVALID"

    # Reproducible-artifact attestation (RC gate v2)
    TAG_MISSING = "TAG_MISSING"
    TAG_NOT_ANNOTATED = "TAG_NOT_ANNOTATED"
    TAG_MOVED = "TAG_MOVED"
    BUILD_COMMAND_INVALID = "BUILD_COMMAND_INVALID"
    BUILD_FAILED = "BUILD_FAILED"
    BUILD_NOT_REPRODUCIBLE = "BUILD_NOT_REPRODUCIBLE"
    ARTIFACT_HASH_UNBACKED = "ARTIFACT_HASH_UNBACKED"
    SOURCE_DELTA_NOT_ALLOWLISTED = "SOURCE_DELTA_NOT_ALLOWLISTED"
    TOOLCHAIN_UNPINNED = "TOOLCHAIN_UNPINNED"

    # Network identity
    NETWORK_MISMATCH = "NETWORK_MISMATCH"
    CHAIN_NAME_MISMATCH = "CHAIN_NAME_MISMATCH"
    ENDPOINT_NOT_PINNED = "ENDPOINT_NOT_PINNED"

    # Cost model
    COST_LINE_UNKNOWN = "COST_LINE_UNKNOWN"
    COST_CEILING_ABSENT = "COST_CEILING_ABSENT"
    COST_CEILING_INVALID = "COST_CEILING_INVALID"
    COST_CEILING_EXCEEDED = "COST_CEILING_EXCEEDED"

    # Economic manifest v2 (plan-derived, principal + fees)
    PRINCIPAL_LINE_ABSENT = "PRINCIPAL_LINE_ABSENT"
    CEILING_ARITHMETIC_INVALID = "CEILING_ARITHMETIC_INVALID"
    CALIBRATION_RECEIPT_ABSENT = "CALIBRATION_RECEIPT_ABSENT"
    AUTHORIZATION_EXPIRED = "AUTHORIZATION_EXPIRED"

    # Calibration v2 (plan-bound Testnet receipts)
    CALIBRATION_LINE_SET_MISMATCH = "CALIBRATION_LINE_SET_MISMATCH"
    CALIBRATION_BINDING_INVALID = "CALIBRATION_BINDING_INVALID"
    OPERATOR_CEILING_NOT_PERMITTED = "OPERATOR_CEILING_NOT_PERMITTED"

    # Custody disclosure
    CUSTODY_MODEL_INVALID = "CUSTODY_MODEL_INVALID"
    CUSTODY_EVIDENCE_ABSENT = "CUSTODY_EVIDENCE_ABSENT"

    # Authenticity of the human authorization (not merely well-formedness)
    AUTHORIZATION_UNSIGNED = "AUTHORIZATION_UNSIGNED"
    AUTHORIZATION_SIGNATURE_INVALID = "AUTHORIZATION_SIGNATURE_INVALID"
    AUTHORIZER_NOT_PINNED = "AUTHORIZER_NOT_PINNED"
    SIGNATURE_BACKEND_UNAVAILABLE = "SIGNATURE_BACKEND_UNAVAILABLE"

    # Evidence depth and cross-binding
    INSUFFICIENT_CONFIRMATIONS = "INSUFFICIENT_CONFIRMATIONS"
    SNAPSHOT_NOT_CORROBORATED = "SNAPSHOT_NOT_CORROBORATED"
    BUNDLE_CROSS_BINDING_INVALID = "BUNDLE_CROSS_BINDING_INVALID"

    # Identity / role inventory
    KEY_INVENTORY_ABSENT = "KEY_INVENTORY_ABSENT"
    KEY_INVENTORY_INVALID = "KEY_INVENTORY_INVALID"
    KEY_INVENTORY_SECRET_MATERIAL = "KEY_INVENTORY_SECRET_MATERIAL"
    ROLE_SET_INVALID = "ROLE_SET_INVALID"
    TESTNET_IDENTITY_REUSE = "TESTNET_IDENTITY_REUSE"
    SECRET_PATH_READ_REFUSED = "SECRET_PATH_READ_REFUSED"

    # Plan / stage
    PLAN_INPUT_ABSENT = "PLAN_INPUT_ABSENT"
    PLAN_INPUT_INVALID = "PLAN_INPUT_INVALID"
    PLAN_HASH_MISMATCH = "PLAN_HASH_MISMATCH"
    ID_RECOMPUTATION_MISMATCH = "ID_RECOMPUTATION_MISMATCH"
    GOLDEN_VECTOR_MISMATCH = "GOLDEN_VECTOR_MISMATCH"
    ENVELOPE_INVALID = "ENVELOPE_INVALID"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    RECIPIENT_MISMATCH = "RECIPIENT_MISMATCH"
    STATE_ROOT_STALE = "STATE_ROOT_STALE"

    # Verification (read-only public RPC evidence)
    NODE_SET_INVALID = "NODE_SET_INVALID"
    NODE_DISAGREEMENT = "NODE_DISAGREEMENT"
    READBACK_MISMATCH = "READBACK_MISMATCH"
    OBSERVATION_ABSENT = "OBSERVATION_ABSENT"
    OBSERVATION_MALFORMED = "OBSERVATION_MALFORMED"
    PROOF_PENDING = "PROOF_PENDING"
    PROOF_UNSIGNED = "PROOF_UNSIGNED"
    PROOF_NOT_MEMBER = "PROOF_NOT_MEMBER"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    PREQUORUM_UNEXPECTED_SUCCESS = "PREQUORUM_UNEXPECTED_SUCCESS"
    WRONG_REFUSAL_CODE = "WRONG_REFUSAL_CODE"
    WRONG_CONTRACT = "WRONG_CONTRACT"
    WRONG_ENTRY_POINT = "WRONG_ENTRY_POINT"
    WRONG_TYPED_ARGS = "WRONG_TYPED_ARGS"
    TRANSFER_MISMATCH = "TRANSFER_MISMATCH"
    AMBIGUOUS_RESULT = "AMBIGUOUS_RESULT"

    # Broadcast guard (disabled in this lane)
    BROADCAST_DISABLED_AUTHORIZATION_ABSENT = (
        "BROADCAST_DISABLED_AUTHORIZATION_ABSENT"
    )
    AUTHORIZATION_INVALID = "AUTHORIZATION_INVALID"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    SUBMISSION_NOT_IMPLEMENTED_IN_PREP = "SUBMISSION_NOT_IMPLEMENTED_IN_PREP"

    # Durable journal
    JOURNAL_ABSENT = "JOURNAL_ABSENT"
    JOURNAL_TAMPERED = "JOURNAL_TAMPERED"
    JOURNAL_CONFLICT = "JOURNAL_CONFLICT"
    JOURNAL_LOCK_HELD = "JOURNAL_LOCK_HELD"
    JOURNAL_PATH_UNSAFE = "JOURNAL_PATH_UNSAFE"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    DUPLICATE_ECONOMIC_ACTION = "DUPLICATE_ECONOMIC_ACTION"

    # CSPR.cloud /supported probe (redacting helper)
    PROBE_HEADER_INVALID = "PROBE_HEADER_INVALID"

    # Proof bundle claims discipline
    FORBIDDEN_CLAIM = "FORBIDDEN_CLAIM"

    # Artifact lineage
    LIVE_ARTIFACTS_UNAVAILABLE_IN_PREP = "LIVE_ARTIFACTS_UNAVAILABLE_IN_PREP"
    CANONICAL_NAMESPACE_PROTECTED = "CANONICAL_NAMESPACE_PROTECTED"


class CanaryRefusal(Exception):
    """A fail-closed refusal with a stable code and a secret-free detail."""

    def __init__(self, code: str, detail: str):
        if not code or not code.isupper():
            raise ValueError("refusal code must be a stable upper-case token")
        self.code = code
        self.detail = detail
        super().__init__(f"{code}: {detail}")

    def as_dict(self) -> dict[str, str]:
        return {"code": self.code, "detail": self.detail}
